// Code generated by protoc-gen-go. DO NOT EDIT.
// source: echo.proto

package echo

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type EchoRequest struct {
	Message              string   `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *EchoRequest) Reset()         { *m = EchoRequest{} }
func (m *EchoRequest) String() string { return proto.CompactTextString(m) }
func (*EchoRequest) ProtoMessage()    {}
func (*EchoRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_08134aea513e0001, []int{0}
}

func (m *EchoRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EchoRequest.Unmarshal(m, b)
}
func (m *EchoRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EchoRequest.Marshal(b, m, deterministic)
}
func (m *EchoRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EchoRequest.Merge(m, src)
}
func (m *EchoRequest) XXX_Size() int {
	return xxx_messageInfo_EchoRequest.Size(m)
}
func (m *EchoRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_EchoRequest.DiscardUnknown(m)
}

var xxx_messageInfo_EchoRequest proto.InternalMessageInfo

func (m *EchoRequest) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

type Echo struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Message              string   `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Created              int64    `protobuf:"varint,3,opt,name=created,proto3" json:"created,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Echo) Reset()         { *m = Echo{} }
func (m *Echo) String() string { return proto.CompactTextString(m) }
func (*Echo) ProtoMessage()    {}
func (*Echo) Descriptor() ([]byte, []int) {
	return fileDescriptor_08134aea513e0001, []int{1}
}

func (m *Echo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Echo.Unmarshal(m, b)
}
func (m *Echo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Echo.Marshal(b, m, deterministic)
}
func (m *Echo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Echo.Merge(m, src)
}
func (m *Echo) XXX_Size() int {
	return xxx_messageInfo_Echo.Size(m)
}
func (m *Echo) XXX_DiscardUnknown() {
	xxx_messageInfo_Echo.DiscardUnknown(m)
}

var xxx_messageInfo_Echo proto.InternalMessageInfo

func (m *Echo) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Echo) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func (m *Echo) GetCreated() int64 {
	if m != nil {
		return m.Created
	}
	return 0
}

type EchoResponse struct {
	Echo                 *Echo    `protobuf:"bytes,1,opt,name=echo,proto3" json:"echo,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *EchoResponse) Reset()         { *m = EchoResponse{} }
func (m *EchoResponse) String() string { return proto.CompactTextString(m) }
func (*EchoResponse) ProtoMessage()    {}
func (*EchoResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_08134aea513e0001, []int{2}
}

func (m *EchoResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EchoResponse.Unmarshal(m, b)
}
func (m *EchoResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EchoResponse.Marshal(b, m, deterministic)
}
func (m *EchoResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EchoResponse.Merge(m, src)
}
func (m *EchoResponse) XXX_Size() int {
	return xxx_messageInfo_EchoResponse.Size(m)
}
func (m *EchoResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_EchoResponse.DiscardUnknown(m)
}

var xxx_messageInfo_EchoResponse proto.InternalMessageInfo

func (m *EchoResponse) GetEcho() *Echo {
	if m != nil {
		return m.Echo
	}
	return nil
}

type EchoHistoryRequest struct {
	Limit                int32    `protobuf:"varint,1,opt,name=limit,proto3" json:"limit,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *EchoHistoryRequest) Reset()         { *m = EchoHistoryRequest{} }
func (m *EchoHistoryRequest) String() string { return proto.CompactTextString(m) }
func (*EchoHistoryRequest) ProtoMessage()    {}
func (*EchoHistoryRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_08134aea513e0001, []int{3}
}

func (m *EchoHistoryRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EchoHistoryRequest.Unmarshal(m, b)
}
func (m *EchoHistoryRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EchoHistoryRequest.Marshal(b, m, deterministic)
}
func (m *EchoHistoryRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EchoHistoryRequest.Merge(m, src)
}
func (m *EchoHistoryRequest) XXX_Size() int {
	return xxx_messageInfo_EchoHistoryRequest.Size(m)
}
func (m *EchoHistoryRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_EchoHistoryRequest.DiscardUnknown(m)
}

var xxx_messageInfo_EchoHistoryRequest proto.InternalMessageInfo

func (m *EchoHistoryRequest) GetLimit() int32 {
	if m != nil {
		return m.Limit
	}
	return 0
}

func init() {
	proto.RegisterType((*EchoRequest)(nil), "net.k2lab.test.grpc.testing.echo.EchoRequest")
	proto.RegisterType((*Echo)(nil), "net.k2lab.test.grpc.testing.echo.Echo")
	proto.RegisterType((*EchoResponse)(nil), "net.k2lab.test.grpc.testing.echo.EchoResponse")
	proto.RegisterType((*EchoHistoryRequest)(nil), "net.k2lab.test.grpc.testing.echo.EchoHistoryRequest")
}

func init() { proto.RegisterFile("echo.proto", fileDescriptor_08134aea513e0001) }

var fileDescriptor_08134aea513e0001 = []byte{
	// 251 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x52, 0x3f, 0x4b, 0xc4, 0x30,
	0x14, 0x27, 0xbd, 0x3f, 0xe2, 0x3b, 0x71, 0x08, 0x0e, 0xc5, 0xa9, 0x74, 0xd0, 0x43, 0xf0, 0x21,
	0xd5, 0xc9, 0x51, 0x10, 0xe4, 0xc6, 0xba, 0xb9, 0xf5, 0xd2, 0x47, 0x2f, 0x78, 0xd7, 0xd4, 0xe4,
	0x9d, 0xe0, 0x67, 0xf6, 0x4b, 0x48, 0x92, 0x16, 0xec, 0x64, 0xdd, 0xfa, 0xe3, 0xfd, 0xfe, 0x96,
	0x00, 0x90, 0xda, 0x19, 0xec, 0xac, 0x61, 0x23, 0xb3, 0x96, 0x18, 0xdf, 0x8b, 0x7d, 0xb5, 0x45,
	0x26, 0xc7, 0xd8, 0xd8, 0x4e, 0x85, 0x2f, 0xdd, 0x36, 0xe8, 0x79, 0xf9, 0x35, 0xac, 0x9e, 0xd5,
	0xce, 0x94, 0xf4, 0x71, 0x24, 0xc7, 0x32, 0x85, 0x93, 0x03, 0x39, 0x57, 0x35, 0x94, 0x8a, 0x4c,
	0xac, 0x4f, 0xcb, 0x01, 0xe6, 0x1b, 0x98, 0x7b, 0xa2, 0x3c, 0x87, 0x44, 0xd7, 0xfd, 0x31, 0xd1,
	0xf5, 0x6f, 0x45, 0x32, 0x52, 0xf8, 0x8b, 0xb2, 0x54, 0x31, 0xd5, 0xe9, 0x2c, 0x13, 0xeb, 0x59,
	0x39, 0xc0, 0x7c, 0x03, 0x67, 0x31, 0xd4, 0x75, 0xa6, 0x75, 0x24, 0x1f, 0x61, 0xee, 0xcb, 0x04,
	0xd7, 0x55, 0x71, 0x85, 0x7f, 0xb5, 0xc6, 0xa0, 0x0e, 0x9a, 0xfc, 0x06, 0xa4, 0x47, 0x2f, 0xda,
	0xb1, 0xb1, 0x5f, 0xc3, 0x8e, 0x0b, 0x58, 0xec, 0xf5, 0x41, 0x73, 0xb0, 0x5c, 0x94, 0x11, 0x14,
	0xdf, 0x22, 0xae, 0x7d, 0x25, 0xfb, 0xa9, 0x15, 0x49, 0xea, 0x37, 0xdd, 0x4e, 0x4c, 0x8c, 0xe6,
	0x97, 0x38, 0x95, 0xde, 0xcf, 0x3b, 0xc6, 0xd4, 0xbe, 0xa2, 0x7c, 0x98, 0x26, 0x1f, 0x2f, 0xfa,
	0x6f, 0xe8, 0x9d, 0x78, 0x5a, 0xbe, 0x85, 0x3f, 0xb4, 0x5d, 0x86, 0xb7, 0x70, 0xff, 0x13, 0x00,
	0x00, 0xff, 0xff, 0x22, 0x9d, 0x4b, 0x41, 0x19, 0x02, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// EchoServiceClient is the client API for EchoService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type EchoServiceClient interface {
	Echo(ctx context.Context, in *EchoRequest, opts ...grpc.CallOption) (*EchoResponse, error)
	EchoHistory(ctx context.Context, in *EchoHistoryRequest, opts ...grpc.CallOption) (EchoService_EchoHistoryClient, error)
}

type echoServiceClient struct {
	cc *grpc.ClientConn
}

func NewEchoServiceClient(cc *grpc.ClientConn) EchoServiceClient {
	return &echoServiceClient{cc}
}

func (c *echoServiceClient) Echo(ctx context.Context, in *EchoRequest, opts ...grpc.CallOption) (*EchoResponse, error) {
	out := new(EchoResponse)
	err := c.cc.Invoke(ctx, "/net.k2lab.test.grpc.testing.echo.EchoService/Echo", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *echoServiceClient) EchoHistory(ctx context.Context, in *EchoHistoryRequest, opts ...grpc.CallOption) (EchoService_EchoHistoryClient, error) {
	stream, err := c.cc.NewStream(ctx, &_EchoService_serviceDesc.Streams[0], "/net.k2lab.test.grpc.testing.echo.EchoService/EchoHistory", opts...)
	if err != nil {
		return nil, err
	}
	x := &echoServiceEchoHistoryClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type EchoService_EchoHistoryClient interface {
	Recv() (*EchoResponse, error)
	grpc.ClientStream
}

type echoServiceEchoHistoryClient struct {
	grpc.ClientStream
}

func (x *echoServiceEchoHistoryClient) Recv() (*EchoResponse, error) {
	m := new(EchoResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// EchoServiceServer is the server API for EchoService service.
type EchoServiceServer interface {
	Echo(context.Context, *EchoRequest) (*EchoResponse, error)
	EchoHistory(*EchoHistoryRequest, EchoService_EchoHistoryServer) error
}

func RegisterEchoServiceServer(s *grpc.Server, srv EchoServiceServer) {
	s.RegisterService(&_EchoService_serviceDesc, srv)
}

func _EchoService_Echo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EchoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EchoServiceServer).Echo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/net.k2lab.test.grpc.testing.echo.EchoService/Echo",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EchoServiceServer).Echo(ctx, req.(*EchoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _EchoService_EchoHistory_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(EchoHistoryRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(EchoServiceServer).EchoHistory(m, &echoServiceEchoHistoryServer{stream})
}

type EchoService_EchoHistoryServer interface {
	Send(*EchoResponse) error
	grpc.ServerStream
}

type echoServiceEchoHistoryServer struct {
	grpc.ServerStream
}

func (x *echoServiceEchoHistoryServer) Send(m *EchoResponse) error {
	return x.ServerStream.SendMsg(m)
}

var _EchoService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "net.k2lab.test.grpc.testing.echo.EchoService",
	HandlerType: (*EchoServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Echo",
			Handler:    _EchoService_Echo_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "EchoHistory",
			Handler:       _EchoService_EchoHistory_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "echo.proto",
}
